image:
  repository: ghcr.io/xataio/xata/auth
  tag: latest
  pullPolicy: IfNotPresent

service:
  httpPort: 5001
  grpcPort: 5002

dependencies:
  authGrpcUrl: "auth:5002"
  projectsGrpcUrl: "projects:5002"

postgres:
  sslmode: disable

observability:
  serviceName: auth

config:
  frontendURL: ""
  billingRequired: false

httpRoute:
  hostname: localhost

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - auth
          topologyKey: kubernetes.io/hostname

tolerations:
  - key: "xata.io/workload"
    value: "controlplane"
    effect: "NoSchedule"

resourceCleanup:
  schedule: "0 10 * * *"
  disabledForDays: 15
  maxBranches: 50
  dryRun: true
  suspend: false
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi

trialExpiryEmails:
  schedule: "0 9 * * *"
  timeZone: "Etc/UTC"
  suspend: false
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
