apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-branches
subjects:
  - kind: ServiceAccount
    name: clusters
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: access-branches
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-cnpg
  namespace: {{ .Values.config.clusters.clustersNamespace }}
subjects:
  - kind: ServiceAccount
    name: clusters
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-cnpg
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-ipfiltering
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: clusters
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-ipfiltering
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-services-xata
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: clusters
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-services-xata
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-services-clusters
  namespace: {{ .Values.config.clusters.clustersNamespace }}
subjects:
  - kind: ServiceAccount
    name: clusters
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-services-clusters
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cnpg-clusters-scale-to-zero
subjects:
  - kind: Group
    name: system:serviceaccounts:{{ .Values.config.clusters.clustersNamespace }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cnpg-scale-to-zero-sidecar-role
  apiGroup: rbac.authorization.k8s.io
