apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: access-branches
rules:
  - apiGroups:
      - xata.io
    resources:
      - branches
    verbs:
      - create
      - delete
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-cnpg
  namespace: {{ .Values.config.clusters.clustersNamespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - delete
      - get
  - apiGroups:
      - barmancloud.cnpg.io
    resources:
      - objectstores
    verbs:
      - get
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - xata.io
    resources:
      - clusterpools
    verbs:
      - list
  - apiGroups:
      - xata.io
    resources:
      - wakeuprequests
    verbs:
      - create
      - delete
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-ipfiltering
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - ipfiltering
    verbs:
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-services-xata
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-services-clusters
  namespace: {{ .Values.config.clusters.clustersNamespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
