image:
  repository: ghcr.io/xataio/xata/branch-operator
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

config:
  branchOperator:
    imageSecrets: ghcr-secret
    clustersTolerations: "xata.io/workload=dataplane:NoSchedule"
    cloudProvider: aws
    barmanRegionSecret:
      # Without this barman will create a role and bind it to our CNPG pods with
      # '*' permissions to all secrets in the namespace. This is a problem if
      # you get priv esc from postgres. Setting the region secret will scope the
      # role to just that secret and close the hole. With inheritFromIAMRole set
      # to true this has no actual implication since the AWS credential chain is
      # followed as normal and eventually fallback to IMDSv2 for credentials.
      name: barman-dummy-secret
      key: dummy
      value: dummy
    xatastor:
      enabled: true

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - branch-operator
          topologyKey: kubernetes.io/hostname

tolerations:
  - key: "xata.io/workload"
    value: "dataplane"
    effect: "NoSchedule"
