apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.branchOperator.barmanRegionSecret.name | quote }}
  namespace: xata-clusters
  labels:
    app: branch-operator
type: Opaque
stringData:
  {{ .Values.config.branchOperator.barmanRegionSecret.key | quote }}: {{ .Values.config.branchOperator.barmanRegionSecret.value | quote }}
