apiVersion: v1
kind: ConfigMap
metadata:
  name: branch-operator-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: branch-operator
data:
  XATA_IMAGE_SECRETS: {{ .Values.config.branchOperator.imageSecrets | quote }}
  XATA_CLUSTERS_TOLERATIONS: {{ .Values.config.branchOperator.clustersTolerations | quote }}
  XATA_BARMAN_REGION_SECRET_NAME: {{ .Values.config.branchOperator.barmanRegionSecret.name | quote }}
  XATA_BARMAN_REGION_SECRET_KEY: {{ .Values.config.branchOperator.barmanRegionSecret.key | quote }}
  XATA_XATASTOR_ENABLED: {{ .Values.config.branchOperator.xatastor.enabled | quote }}
