// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	context "context"
	provisioner "xata/services/projects/provisioner"

	mock "github.com/stretchr/testify/mock"

	store "xata/services/projects/store"
)

// Provisioner is an autogenerated mock type for the Provisioner type
type Provisioner struct {
	mock.Mock
}

type Provisioner_Expecter struct {
	mock *mock.Mock
}

func (_m *Provisioner) EXPECT() *Provisioner_Expecter {
	return &Provisioner_Expecter{mock: &_m.Mock}
}

// CreateBranch provides a mock function with given fields: ctx, projectID, organizationID, name, payload
func (_m *Provisioner) CreateBranch(ctx context.Context, projectID string, organizationID string, name string, payload *provisioner.ClusterServicePayload) (*store.Branch, error) {
	ret := _m.Called(ctx, projectID, organizationID, name, payload)

	var r0 *store.Branch
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *provisioner.ClusterServicePayload) *store.Branch); ok {
		r0 = rf(ctx, projectID, organizationID, name, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Branch)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *provisioner.ClusterServicePayload) error); ok {
		r1 = rf(ctx, projectID, organizationID, name, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Provisioner_CreateBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBranch'
type Provisioner_CreateBranch_Call struct {
	*mock.Call
}

// CreateBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - organizationID string
//   - name string
//   - payload *provisioner.ClusterServicePayload
func (_e *Provisioner_Expecter) CreateBranch(ctx interface{}, projectID interface{}, organizationID interface{}, name interface{}, payload interface{}) *Provisioner_CreateBranch_Call {
	return &Provisioner_CreateBranch_Call{Call: _e.mock.On("CreateBranch", ctx, projectID, organizationID, name, payload)}
}

func (_c *Provisioner_CreateBranch_Call) Run(run func(ctx context.Context, projectID string, organizationID string, name string, payload *provisioner.ClusterServicePayload)) *Provisioner_CreateBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*provisioner.ClusterServicePayload))
	})
	return _c
}

func (_c *Provisioner_CreateBranch_Call) Return(_a0 *store.Branch, _a1 error) *Provisioner_CreateBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewProvisioner interface {
	mock.TestingT
	Cleanup(func())
}

// NewProvisioner creates a new instance of Provisioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProvisioner(t mockConstructorTestingTNewProvisioner) *Provisioner {
	mock := &Provisioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
