// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Execute SQL query
	// (POST /sql)
	Query(ctx echo.Context, params QueryParams) error
	// WebSocket wire protocol proxy
	// (GET /v2)
	Websocket(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Query converts echo context to params.
func (w *ServerInterfaceWrapper) Query(ctx echo.Context) error {
	var err error

	ctx.Set(BranchConnectionStringScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params QueryParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "Array-Mode" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Array-Mode")]; found {
		var ArrayMode QueryParamsArrayMode
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Array-Mode, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Array-Mode", valueList[0], &ArrayMode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Array-Mode: %s", err))
		}

		params.ArrayMode = &ArrayMode
	}
	// ------------- Optional header parameter "Raw-Text-Output" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Raw-Text-Output")]; found {
		var RawTextOutput QueryParamsRawTextOutput
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Raw-Text-Output, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Raw-Text-Output", valueList[0], &RawTextOutput, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Raw-Text-Output: %s", err))
		}

		params.RawTextOutput = &RawTextOutput
	}
	// ------------- Optional header parameter "Batch-Isolation-Level" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Isolation-Level")]; found {
		var BatchIsolationLevel QueryParamsBatchIsolationLevel
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Isolation-Level, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Isolation-Level", valueList[0], &BatchIsolationLevel, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Isolation-Level: %s", err))
		}

		params.BatchIsolationLevel = &BatchIsolationLevel
	}
	// ------------- Optional header parameter "Batch-Read-Only" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Read-Only")]; found {
		var BatchReadOnly QueryParamsBatchReadOnly
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Read-Only, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Read-Only", valueList[0], &BatchReadOnly, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Read-Only: %s", err))
		}

		params.BatchReadOnly = &BatchReadOnly
	}
	// ------------- Optional header parameter "Batch-Deferrable" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Deferrable")]; found {
		var BatchDeferrable QueryParamsBatchDeferrable
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Deferrable, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Deferrable", valueList[0], &BatchDeferrable, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Deferrable: %s", err))
		}

		params.BatchDeferrable = &BatchDeferrable
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Query(ctx, params)
	return err
}

// Websocket converts echo context to params.
func (w *ServerInterfaceWrapper) Websocket(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Websocket(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/sql", wrapper.Query)
	router.GET(baseURL+"/v2", wrapper.Websocket)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa/W7bSJJ/lQIvwEmGJH8kuTvocMA4sTLjOyd2LOWygG2ALbIk9oTsZrqbspXAwD7E",
	"PuE+yaK6mx+SKEVOZgezwPyTWGR3VXV9/Oqj+TWIZJZLgcLoYPg10FGCGbN/vmImSq5R51JopAcx6kjx",
	"3HApgmFQvoGZVMBgSqvhc4FqCfiAUUHLBkEvyJXMURmOlqhCXaSO1QY5emGpIatIcQEmQUe9R7+kilER",
	"XW4ws3SeKZwFw+DfDuuTHPpjHL4nIo508NgLzDLHYBgwpdgyeHzsBQo/F1xhHAxvKtHuqnVy+itGduNI",
	"Kam268K+BlVq5J6bBK6kNnOF4/cXgPb1jGMa602VRDJuIbmxnZZBZ/z+Yjw5nYy6QFrP85RHjHY0FhEH",
	"fwBtFBdzOkAk0yITm2xe2+cgWIagMGUGYzDS6txS3EJMaKMYF6aNYPnuiURjZtjEPlwnecYMA1r/VIpo",
	"GE836V3aP1gKbgFkqDWbt+ttxtMWicayUBECvYT7BBXWksA906Awl4pk7GhUC1R9zWPstjJIWrVYiUiv",
	"bUwo1DJdcDH/xqG5MKgES6+k5o5Yi2fZNxRNjP51G9Jlf44CldWtDb6d9G1kbRKf4IMBObNCPpFyysV2",
	"VdPLH1W1t/Mmj1+KjIm+QhazaVoS3+UV+Vblvk6YYpFBBXlDzSSyw7P1I8goKpTCuJWNkoXZpRT//kf1",
	"4sCyhYt9/sSg07hAxc1yD0Qrl0IHB/MBhKPr68vrsAfhm9PJ6UXYLqwhE7X4nbXc00S1amtFMENezAXc",
	"JzxK9rPWWjIpfa0tmbyhRHCGMy62R2ipKYfbkKFhBJAwUzKzAil5D41dTXddTy9E4fxsk82pMYpPC4Mg",
	"imyKqoxbz5OymPddq3QiPZMqYyYYEgw8P6m1QKE+RxX0gof+XPb904ILc/wfTXBvE+Py/GyNc1wC/vex",
	"fH7SZPlWxnzGUbX4zDLHvs4x4jMeQebXeW/MFUZccykOdcRSV+WIIkPFIyua7u4jXEOOMf+yM7dp/gWh",
	"I3DODF84fgumOGm+n6KYm+QJfFeVUpmh3NYqhXsJnZC8P6T6IpxywdRySyRSsO0sKLbH7zfcQDt4s0uh",
	"cwR8BkIaYP6J85Lu9zvHWqzag9SS9eqQWXHcNVO2eFglT1vU24R5bjBrCUTQXMzTKke4wCtrahIVtdmM",
	"bFvGvm2tHi8XqBSPEewa8m3nUSbhGriI+YLHBUs3svFUyhSZsDmOKZbp7eUDS8EuQYNKe+JYEyzL842q",
	"uxd8bi8dCO6cAoz0LQR+G2gdsa0K97X/lnaDHI6Vyq/57+hfIpllTMTfwGy7Bgybl6ltPLoYvZ5Qbjt/",
	"Nx5d278+XJ2dTkb019noYjQZbQkz1zZsDbQ6M3gLuDYGNJq9u6T1hNRiMyXvT/Wp/bUhyccETYKKUpIG",
	"pkgEUyiBMTDtHFATqqgCQ9u2OBPRsxlLNa6cu+GASt6/lkVbdfyuSleO5WyGEWX86dJnEat/oiqKNHUF",
	"A7Fvg2eisNU96OUARtSOUr7lmgpmJz50HEr0bc3xCZfatWTCh1znPkHRDD+uAQXJEnd3xccqYjGx2ad6",
	"h+hVvthQlT/Pir3aYmP8/uLawcquOCyRB66UXBCaILeGDu3r0Hf+K9gl/VuOOmxOBn479HJ8Oitc7Qop",
	"0mX3N8cy6ITPjilIn52EPRgMBt090M0fcQ3l7WHkDPwKy8dBfAU4Nfb78xnFhGZRCUb7Dz1spvkx8G1R",
	"crcdkNf8y7YBUUG1ve0hnDamiokoeS2FQHuesdu/Icoruw5WALXcA44pdMLcvdbDw8NCoxrmTOufvjoe",
	"j4OvCudcisfBAzNsYDBKDuNp2O0BF1FaxFUbnU0xjjEG2n0vVTyASYKQSG1sWGtMLVK5GljN0YDj0APH",
	"oAcE9CjiXFKjbgu5Dq0O++o+PAz7Soagi9mMP/RAI0I48mupcCCBaH9WaAOZ9QSH4DbsrBgDuJwaxgVw",
	"U9f+fyG8j5lOppKpGLy7RlIYJdN+njKBcHp1ToehdO/kp/CASGGMwnCW2mdzZvCeLYFFEeZG/3c7HUI3",
	"6LxCplCBkZ9QdImowl8d7FIbNYA3XoyPOB3L6BOaWi2d8OfRBA4XJ2HX1Xek202jck0PF7jEGBac2aUN",
	"L9CGKVPkZacDXGiDLHZFI9eQICtHg+RG7mdQ1qlB7Xh973l1cOT8/5CA1s43ZtIlemFYZOHRE9BFTi31",
	"T9aluHQTppV+ojTNz16tuYNNDVmRGp6n9aEX1PZKu9HhQOOclM2nTKMe3opb0YeDg18mkysqTw4OoBNe",
	"XY4ncKg/p2EX/v7Xv4Fr71PUJTRWaie6PoLJyxzU2Pa7hBtHvrKYpV+biqg35LrnCulIRkYypT8eliAX",
	"qGqLe3K07sqvOziwZIRralpjWoMUQJqFly+en9wKsgs3lLODUpGnV+dBL1ig0k7Tx4MjUr/MUbCcB8Pg",
	"+eBocEQphpnEgg0piP4nmGiZ13qAa6n9GsPsBlSzOSN3A9Y8goOCAVnp4OC0MAlFlhvHDg8OQCPVgAn6",
	"df+ud0Oaa7VvRbjhqGHp2hac9gxPkklIMqkLboxJzc2gt/DihL+2g6Q5Sf0kqKNiz7BPKCpsuhUVeFbg",
	"6ocIG0fu+fnKLvi7FWN0o602vZRZBmzqwypz01bfz/oTjhuZjI7pQ7MqZTp0OFlOXUNXMIRdYMZpROaQ",
	"4gJTT87ejWzQsUUP03UR6D1oWZa8PbBjL+8X5UGnMl7eCtoH/zu+fOf2DuBVdaNCHljm5F0Fgo0dqrGs",
	"D57HwdA1QYGvgGx5EwxvWgp4Aa5A7/ni3VfWVf3eAFt/lq1Aa+ucvq3smrNFFEVG5SuxoU6ZSv9GbVpX",
	"E/tIx9IUFiwt0Mro9mqrG1l437SpxALGVkmv2X1/gg+mf1mYvDC/jbiT2iDAtUzd9Yx1nkbF5826VTRr",
	"/P55ub9/QftbBbxGFr+WWcaNQeoF6PcHEa08yZHZ6Qa9C3rBGBVnKf9iO6Mnm6D0xOperumDFOwKWdy3",
	"5Ubmr6N2HJFE6l+KdPlPcJZvShrjDJWyQ6U9RD2rVn+XrHeujUNtXsl4WdYY6BrcxlXe4a/aDYXxgWV5",
	"6otnksBe0BZZxqiCd0I1kxQXIMUKIlDSpCihjVVfcvO16oduggTTVJK0vi8I3HwCzt9NLiGVcw0dX291",
	"4f9PLz6MxtB5dtwNSPPlFjfcgIg60M5BF95cX761e4PHO9sLWKRaFd7jcQVL/Et5N9SUuZLzxUlDRM+P",
	"xz038Lf8qAnQ8PGX0fUIeAz/A8+OXUFXG2pXz9RoiB9XG24yq33gLnetNU6Ojn7cfvUIqvZPNpUL7Fkz",
	"ojBqCTmqTbVUl+g3jYGUt1xQT4xu7lbnNtYzm3OV43L8cXNH9qxJOQ03STXvEY5W5/knR23D9v7x+uj7",
	"vxrjWoMPpg6vyM8uqtnw0eP+on/124fBMfnbVo9bVfdKZ2u13lTw92ri+X6aeLFVEzxeVUNvF7eX+3Gj",
	"J1vYrU2+n6h3HgfDFyd13o+ZDfiVmJMCL2d29f6faexeu/pZime4mgTeN6a4GIMuogi1nhVpakcgL/aK",
	"3v1wY/XDkBZZzsWCpTyuij2poLoBdcIc/37CvOWaHJ+E4F6ujaqchHr5+2rIfSbgO9laNS+P/vP3k6L6",
	"nMlICSk1QCtzLOvC2yZYN3cUN078tvq6ORRYmzChiGSMLRMm2225zovKkkKlVJcYk+vh4eGOOZeFMXdt",
	"2Ji6uRZ4xuxdSJAt+/5xr332dn42gA8aG90rhDwOe/DucgLcaEhWv5iwCGCT5Ly60C6ZFbqPTJv+8TZm",
	"/pBWL2G1OgRPwk7dIU9ZhIlMY1RuZMaW9k5wir6VIhoE7ktZqGqEMiBLk2mqLFB2/lXDb+Fvbmshb6Hg",
	"7vFPY/5hjfnYCw4XJyTVHFsmOx/yuWIxRTGwxiiygXImYcZOr7i31LYR1+BW2HlLylEY27Vrb8cI+QJX",
	"xjnVWMwXy9pNxtz9eUOOGZW7euvIqBqOejttTokaA1ym3cClnA7WsxmuqRyOezAtDHD7WxcEnTsHq7ei",
	"MVnlsbPF6tBPMXv/YxJmPx2znBuzqVux7+zYXuf7uVTb2OIjTrXVWLBWeR+7dLl2eXHPTZSQesqxo7ZT",
	"x1b7o6Zyh+sE40YxsObMrE7YRKiwF3fkVIX3r5qgTxN/wsUfHvtrd2gZZf+ZB/7F8sBjZbCdn2I07lsI",
	"+kqw7MFOb3DDbn9rsZoV6u6p9JPHu8d/BAAA//+oCVnhRy8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
