// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package spec

const (
	BranchConnectionStringScopes = "branchConnectionString.Scopes"
)

// Defines values for QueryParamsArrayMode.
const (
	QueryParamsArrayModeFalse QueryParamsArrayMode = "false"
	QueryParamsArrayModeTrue  QueryParamsArrayMode = "true"
)

// Defines values for QueryParamsRawTextOutput.
const (
	QueryParamsRawTextOutputFalse QueryParamsRawTextOutput = "false"
	QueryParamsRawTextOutputTrue  QueryParamsRawTextOutput = "true"
)

// Defines values for QueryParamsBatchIsolationLevel.
const (
	ReadCommitted   QueryParamsBatchIsolationLevel = "ReadCommitted"
	ReadUncommitted QueryParamsBatchIsolationLevel = "ReadUncommitted"
	RepeatableRead  QueryParamsBatchIsolationLevel = "RepeatableRead"
	Serializable    QueryParamsBatchIsolationLevel = "Serializable"
)

// Defines values for QueryParamsBatchReadOnly.
const (
	QueryParamsBatchReadOnlyFalse QueryParamsBatchReadOnly = "false"
	QueryParamsBatchReadOnlyTrue  QueryParamsBatchReadOnly = "true"
)

// Defines values for QueryParamsBatchDeferrable.
const (
	QueryParamsBatchDeferrableFalse QueryParamsBatchDeferrable = "false"
	QueryParamsBatchDeferrableTrue  QueryParamsBatchDeferrable = "true"
)

// BatchResponse Response for a batch query execution.
type BatchResponse struct {
	// Results Results for each query in the batch, in order.
	Results []QueryResult `json:"results"`
}

// ErrorResponse Error response with PostgreSQL error fields.
type ErrorResponse struct {
	// Code PostgreSQL error code (SQLSTATE) or application error code.
	Code *string `json:"code,omitempty"`

	// Column Column name related to the error.
	Column *string `json:"column,omitempty"`

	// Constraint Constraint name related to the error.
	Constraint *string `json:"constraint,omitempty"`

	// DataType Data type name related to the error.
	DataType *string `json:"dataType,omitempty"`

	// Detail Optional detail message.
	Detail *string `json:"detail,omitempty"`

	// File Source file where the error was reported (server-side).
	File *string `json:"file,omitempty"`

	// Hint Optional hint for resolving the error.
	Hint *string `json:"hint,omitempty"`

	// InternalPosition Position in an internally-generated query.
	InternalPosition *string `json:"internalPosition,omitempty"`

	// InternalQuery Text of the internally-generated query.
	InternalQuery *string `json:"internalQuery,omitempty"`

	// Line Source line where the error was reported (server-side).
	Line *string `json:"line,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`

	// Position Character position in the query where the error occurred.
	Position *string `json:"position,omitempty"`

	// Routine Source routine where the error was reported (server-side).
	Routine *string `json:"routine,omitempty"`

	// Schema Schema name related to the error.
	Schema *string `json:"schema,omitempty"`

	// Severity PostgreSQL error severity (e.g. `ERROR`, `FATAL`).
	Severity *string `json:"severity,omitempty"`

	// Table Table name related to the error.
	Table *string `json:"table,omitempty"`

	// Where Context in which the error occurred.
	Where *string `json:"where,omitempty"`
}

// FieldDefinition PostgreSQL column metadata from the row description message.
type FieldDefinition struct {
	// ColumnID Attribute number of the column within the table.
	ColumnID uint16 `json:"columnID"`

	// DataTypeID OID of the column data type.
	DataTypeID uint32 `json:"dataTypeID"`

	// DataTypeModifier Type-specific modifier (e.g. precision/scale for numeric types).
	DataTypeModifier int32 `json:"dataTypeModifier"`

	// DataTypeSize Data type size (negative for variable-length types).
	DataTypeSize int16 `json:"dataTypeSize"`

	// Format Data format (`text` or `binary`).
	Format string `json:"format"`

	// Name Column name.
	Name string `json:"name"`

	// TableID OID of the source table (0 if not a table column).
	TableID uint32 `json:"tableID"`
}

// QueryItem A single query within a batch request.
type QueryItem struct {
	// ArrayMode Override array mode for this individual query.
	ArrayMode *bool `json:"arrayMode,omitempty"`

	// Params Positional parameters for the query.
	Params *[]interface{} `json:"params,omitempty"`

	// Query SQL query to execute.
	Query string `json:"query"`
}

// QueryResult Result of a single SQL query execution.
type QueryResult struct {
	// Command PostgreSQL command tag (e.g. `SELECT`, `INSERT`, `UPDATE`, `DELETE`).
	Command string `json:"command"`

	// Fields Column metadata for the result set.
	Fields []FieldDefinition `json:"fields"`

	// RowAsArray Whether rows are returned as arrays (`true`) or objects (`false`).
	RowAsArray bool `json:"rowAsArray"`

	// RowCount Number of rows affected by the command.
	RowCount *int `json:"rowCount"`

	// Rows Result rows. Each row is an object (column-name keys) or an array (when array mode is enabled).
	Rows any `json:"rows"`
}

// SQLRequest SQL query request. Provide either `query` for a single query or `queries` for a batch.
type SQLRequest struct {
	// ArrayMode Override array mode for this query (single query mode only).
	ArrayMode *bool `json:"arrayMode,omitempty"`

	// Params Positional parameters for the query (`$1`, `$2`, ...).
	Params *[]interface{} `json:"params,omitempty"`

	// Queries Array of queries for batch execution within a single transaction.
	Queries *[]QueryItem `json:"queries,omitempty"`

	// Query SQL query to execute (single query mode).
	Query *string `json:"query,omitempty"`
}

// QueryParams defines parameters for Query.
type QueryParams struct {
	// ArrayMode When `true`, return rows as arrays instead of objects.
	ArrayMode *QueryParamsArrayMode `json:"Array-Mode,omitempty"`

	// RawTextOutput When `true`, return all values as strings without type conversion.
	RawTextOutput *QueryParamsRawTextOutput `json:"Raw-Text-Output,omitempty"`

	// BatchIsolationLevel Transaction isolation level for batch queries.
	BatchIsolationLevel *QueryParamsBatchIsolationLevel `json:"Batch-Isolation-Level,omitempty"`

	// BatchReadOnly When `true`, execute the batch transaction in read-only mode.
	BatchReadOnly *QueryParamsBatchReadOnly `json:"Batch-Read-Only,omitempty"`

	// BatchDeferrable When `true`, execute the batch transaction in deferrable mode.
	BatchDeferrable *QueryParamsBatchDeferrable `json:"Batch-Deferrable,omitempty"`
}

// QueryParamsArrayMode defines parameters for Query.
type QueryParamsArrayMode string

// QueryParamsRawTextOutput defines parameters for Query.
type QueryParamsRawTextOutput string

// QueryParamsBatchIsolationLevel defines parameters for Query.
type QueryParamsBatchIsolationLevel string

// QueryParamsBatchReadOnly defines parameters for Query.
type QueryParamsBatchReadOnly string

// QueryParamsBatchDeferrable defines parameters for Query.
type QueryParamsBatchDeferrable string

// QueryJSONRequestBody defines body for Query for application/json ContentType.
type QueryJSONRequestBody = SQLRequest
