image:
  repository: xatatech/clusters
  tag: latest

config:
  clusters:
    storageClass: "csi-hostpath-sc"
    tolerations: "xata.io/workload=dataplane:NoSchedule"
    useOperatorForNewBranches: "true"
    volumeSnapshotClass: "csi-hostpath-snapclass"
    openebs:
      enabled: false
      namespace: openebs
    pgbackrest:
      bucket: "backups"
      region: "us-east-1"
      endpoint: "http://minio-eu.xata-clusters:9000"
